### ISSUE TITLE
An updated blog post about Hack2Learn and Hacker Symposium

### ISSUE THREAD

**Issue by koronkowy** [pascalpdx/pascalpdx.org#6]
Talk about what we've been doing, what we've learned so far, what events happened and what we covered, say something about how it's okay to miss events but also we're progressing as a group, etc. etc.

**Comment by lokkju** [comment]
added via pull request

**Comment by koronkowy** [comment]
I meant this to be a post about what they are, not the particular instance / event.
Like a blog post going over what we've been learning during hacker symposium and hack to learn.

**Comment by koronkowy** [comment]
PASCAL does not exist anymore. Unnecessary to add these ongoing event pages.
